
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:14 GMT 2016 ///

/// interface java.lang.Appendable ///

public protocol Appendable: JavaProtocol {

    /// public abstract java.lang.Appendable java.lang.Appendable.append(java.lang.CharSequence) throws java.io.IOException

    func append( arg0: CharSequence? ) throws /* java.io.IOException */ -> Appendable!
    func append( _ _arg0: CharSequence? ) throws /* java.io.IOException */ -> Appendable!

    /// public abstract java.lang.Appendable java.lang.Appendable.append(java.lang.CharSequence,int,int) throws java.io.IOException

    func append( arg0: CharSequence?, arg1: Int, arg2: Int ) throws /* java.io.IOException */ -> Appendable!
    func append( _ _arg0: CharSequence?, _ _arg1: Int, _ _arg2: Int ) throws /* java.io.IOException */ -> Appendable!

    /// public abstract java.lang.Appendable java.lang.Appendable.append(char) throws java.io.IOException

    func append( arg0: UInt16 ) throws /* java.io.IOException */ -> Appendable!
    func append( _ _arg0: UInt16 ) throws /* java.io.IOException */ -> Appendable!

}

open class AppendableForward: JNIObjectForward, Appendable {

    private static var AppendableJNIClass: jclass?

    /// public abstract java.lang.Appendable java.lang.Appendable.append(java.lang.CharSequence) throws java.io.IOException

    private static var append_MethodID_4: jmethodID?

    open func append( arg0: CharSequence? ) throws /* java.io.IOException */ -> Appendable! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "append", methodSig: "(Ljava/lang/CharSequence;)Ljava/lang/Appendable;", methodCache: &AppendableForward.append_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw /* java.io.IOException */ UnclassedObject( javaObject: throwable )
        }
        return __return != nil ? AppendableForward( javaObject: __return ) : nil
    }

    open func append( _ _arg0: CharSequence? ) throws /* java.io.IOException */ -> Appendable! {
        return try append( arg0: _arg0 )
    }

    /// public abstract java.lang.Appendable java.lang.Appendable.append(java.lang.CharSequence,int,int) throws java.io.IOException

    private static var append_MethodID_5: jmethodID?

    open func append( arg0: CharSequence?, arg1: Int, arg2: Int ) throws /* java.io.IOException */ -> Appendable! {
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        __args[2] = JNIType.encode( value: arg2, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "append", methodSig: "(Ljava/lang/CharSequence;II)Ljava/lang/Appendable;", methodCache: &AppendableForward.append_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw /* java.io.IOException */ UnclassedObject( javaObject: throwable )
        }
        return __return != nil ? AppendableForward( javaObject: __return ) : nil
    }

    open func append( _ _arg0: CharSequence?, _ _arg1: Int, _ _arg2: Int ) throws /* java.io.IOException */ -> Appendable! {
        return try append( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// public abstract java.lang.Appendable java.lang.Appendable.append(char) throws java.io.IOException

    private static var append_MethodID_6: jmethodID?

    open func append( arg0: UInt16 ) throws /* java.io.IOException */ -> Appendable! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "append", methodSig: "(C)Ljava/lang/Appendable;", methodCache: &AppendableForward.append_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw /* java.io.IOException */ UnclassedObject( javaObject: throwable )
        }
        return __return != nil ? AppendableForward( javaObject: __return ) : nil
    }

    open func append( _ _arg0: UInt16 ) throws /* java.io.IOException */ -> Appendable! {
        return try append( arg0: _arg0 )
    }

}


