
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:03 GMT 2016 ///

/// interface java.lang.annotation.Documented ///

public protocol Documented: Annotation {

}

open class DocumentedForward: AnnotationForward, Documented {

    private static var DocumentedJNIClass: jclass?

}


