
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:12 GMT 2016 ///

/// class java.lang.Integer ///

open class Integer: Number, JavaComparable {

    public convenience init?( casting object: JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.lang.Integer", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var IntegerJNIClass: jclass?

    /// public static final int java.lang.Integer.MIN_VALUE

    private static var MIN_VALUE_FieldID: jfieldID?

    open static var MIN_VALUE: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "MIN_VALUE", fieldType: "I", fieldCache: &MIN_VALUE_FieldID, className: "java/lang/Integer", classCache: &IntegerJNIClass )
            return JNIType.decode( type: Int(), from: __value )
        }
    }

    /// public static final int java.lang.Integer.MAX_VALUE

    private static var MAX_VALUE_FieldID: jfieldID?

    open static var MAX_VALUE: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "MAX_VALUE", fieldType: "I", fieldCache: &MAX_VALUE_FieldID, className: "java/lang/Integer", classCache: &IntegerJNIClass )
            return JNIType.decode( type: Int(), from: __value )
        }
    }

    /// public static final java.lang.Class java.lang.Integer.TYPE

    private static var TYPE_FieldID: jfieldID?

    open static var TYPE: Class! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TYPE", fieldType: "Ljava/lang/Class;", fieldCache: &TYPE_FieldID, className: "java/lang/Integer", classCache: &IntegerJNIClass )
            return __value != nil ? Class( javaObject: __value ) : nil
        }
    }

    /// static final char[] java.lang.Integer.digits

    /// static final char[] java.lang.Integer.DigitTens

    /// static final char[] java.lang.Integer.DigitOnes

    /// static final int[] java.lang.Integer.sizeTable

    /// private static java.lang.String java.lang.Integer.integerCacheHighPropValue

    /// private final int java.lang.Integer.value

    /// public static final int java.lang.Integer.SIZE

    private static var SIZE_FieldID: jfieldID?

    open static var SIZE: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "SIZE", fieldType: "I", fieldCache: &SIZE_FieldID, className: "java/lang/Integer", classCache: &IntegerJNIClass )
            return JNIType.decode( type: Int(), from: __value )
        }
    }

    /// private static final long java.lang.Integer.serialVersionUID

    /// private static final long java.lang.Number.serialVersionUID

    /// public java.lang.Integer(int)

    private static var new_MethodID_1: jmethodID?

    public convenience init( arg0: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/Integer", classCache: &Integer.IntegerJNIClass, methodSig: "(I)V", methodCache: &Integer.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Int ) {
        self.init( arg0: _arg0 )
    }

    /// public java.lang.Integer(java.lang.String) throws java.lang.NumberFormatException

    private static var new_MethodID_2: jmethodID?

    public convenience init( arg0: String? ) throws {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/Integer", classCache: &Integer.IntegerJNIClass, methodSig: "(Ljava/lang/String;)V", methodCache: &Integer.new_MethodID_2, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            throw NumberFormatException( javaObject: throwable )
        }
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: String? ) throws {
        try self.init( arg0: _arg0 )
    }

    /// public static int java.lang.Integer.numberOfLeadingZeros(int)

    private static var numberOfLeadingZeros_MethodID_3: jmethodID?

    open class func numberOfLeadingZeros( arg0: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "numberOfLeadingZeros", methodSig: "(I)I", methodCache: &numberOfLeadingZeros_MethodID_3, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func numberOfLeadingZeros( _ _arg0: Int ) -> Int {
        return numberOfLeadingZeros( arg0: _arg0 )
    }

    /// public static int java.lang.Integer.numberOfTrailingZeros(int)

    private static var numberOfTrailingZeros_MethodID_4: jmethodID?

    open class func numberOfTrailingZeros( arg0: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "numberOfTrailingZeros", methodSig: "(I)I", methodCache: &numberOfTrailingZeros_MethodID_4, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func numberOfTrailingZeros( _ _arg0: Int ) -> Int {
        return numberOfTrailingZeros( arg0: _arg0 )
    }

    /// public static int java.lang.Integer.bitCount(int)

    private static var bitCount_MethodID_5: jmethodID?

    open class func bitCount( arg0: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "bitCount", methodSig: "(I)I", methodCache: &bitCount_MethodID_5, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func bitCount( _ _arg0: Int ) -> Int {
        return bitCount( arg0: _arg0 )
    }

    /// public boolean java.lang.Integer.equals(java.lang.Object)

    /// public static java.lang.String java.lang.Integer.toString(int,int)

    private static var toString_MethodID_6: jmethodID?

    open class func toString( arg0: Int, arg1: Int ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "toString", methodSig: "(II)Ljava/lang/String;", methodCache: &toString_MethodID_6, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open class func toString( _ _arg0: Int, _ _arg1: Int ) -> String! {
        return toString( arg0: _arg0, arg1: _arg1 )
    }

    /// public static java.lang.String java.lang.Integer.toString(int)

    private static var toString_MethodID_7: jmethodID?

    open class func toString( arg0: Int ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "toString", methodSig: "(I)Ljava/lang/String;", methodCache: &toString_MethodID_7, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open class func toString( _ _arg0: Int ) -> String! {
        return toString( arg0: _arg0 )
    }

    /// public java.lang.String java.lang.Integer.toString()

    /// public int java.lang.Integer.hashCode()

    /// public static int java.lang.Integer.reverseBytes(int)

    private static var reverseBytes_MethodID_8: jmethodID?

    open class func reverseBytes( arg0: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "reverseBytes", methodSig: "(I)I", methodCache: &reverseBytes_MethodID_8, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func reverseBytes( _ _arg0: Int ) -> Int {
        return reverseBytes( arg0: _arg0 )
    }

    /// public int java.lang.Integer.compareTo(java.lang.Object)

    private static var compareTo_MethodID_9: jmethodID?

    open func compareTo( arg0: JavaObject? ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "compareTo", methodSig: "(Ljava/lang/Object;)I", methodCache: &Integer.compareTo_MethodID_9, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open func compareTo( _ _arg0: JavaObject? ) -> Int {
        return compareTo( arg0: _arg0 )
    }

    /// public int java.lang.Integer.compareTo(java.lang.Integer)

    private static var compareTo_MethodID_10: jmethodID?

    open func compareTo( arg0: Integer? ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "compareTo", methodSig: "(Ljava/lang/Integer;)I", methodCache: &Integer.compareTo_MethodID_10, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open func compareTo( _ _arg0: Integer? ) -> Int {
        return compareTo( arg0: _arg0 )
    }

    /// public byte java.lang.Integer.byteValue()

    /// public short java.lang.Integer.shortValue()

    /// public int java.lang.Integer.intValue()

    /// public long java.lang.Integer.longValue()

    /// public float java.lang.Integer.floatValue()

    /// public double java.lang.Integer.doubleValue()

    /// public static java.lang.Integer java.lang.Integer.valueOf(java.lang.String,int) throws java.lang.NumberFormatException

    private static var valueOf_MethodID_11: jmethodID?

    open class func valueOf( arg0: String?, arg1: Int ) throws /* java.lang.NumberFormatException */ -> Integer! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/String;I)Ljava/lang/Integer;", methodCache: &valueOf_MethodID_11, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw NumberFormatException( javaObject: throwable )
        }
        return __return != nil ? Integer( javaObject: __return ) : nil
    }

    open class func valueOf( _ _arg0: String?, _ _arg1: Int ) throws /* java.lang.NumberFormatException */ -> Integer! {
        return try valueOf( arg0: _arg0, arg1: _arg1 )
    }

    /// public static java.lang.Integer java.lang.Integer.valueOf(java.lang.String) throws java.lang.NumberFormatException

    private static var valueOf_MethodID_12: jmethodID?

    open class func valueOf( arg0: String? ) throws /* java.lang.NumberFormatException */ -> Integer! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/String;)Ljava/lang/Integer;", methodCache: &valueOf_MethodID_12, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw NumberFormatException( javaObject: throwable )
        }
        return __return != nil ? Integer( javaObject: __return ) : nil
    }

    open class func valueOf( _ _arg0: String? ) throws /* java.lang.NumberFormatException */ -> Integer! {
        return try valueOf( arg0: _arg0 )
    }

    /// public static java.lang.Integer java.lang.Integer.valueOf(int)

    private static var valueOf_MethodID_13: jmethodID?

    open class func valueOf( arg0: Int ) -> Integer! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "valueOf", methodSig: "(I)Ljava/lang/Integer;", methodCache: &valueOf_MethodID_13, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Integer( javaObject: __return ) : nil
    }

    open class func valueOf( _ _arg0: Int ) -> Integer! {
        return valueOf( arg0: _arg0 )
    }

    /// public static java.lang.String java.lang.Integer.toHexString(int)

    private static var toHexString_MethodID_14: jmethodID?

    open class func toHexString( arg0: Int ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "toHexString", methodSig: "(I)Ljava/lang/String;", methodCache: &toHexString_MethodID_14, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open class func toHexString( _ _arg0: Int ) -> String! {
        return toHexString( arg0: _arg0 )
    }

    /// static void java.lang.Integer.getChars(int,int,char[])

    /// public static java.lang.Integer java.lang.Integer.decode(java.lang.String) throws java.lang.NumberFormatException

    private static var decode_MethodID_15: jmethodID?

    open class func decode( arg0: String? ) throws /* java.lang.NumberFormatException */ -> Integer! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "decode", methodSig: "(Ljava/lang/String;)Ljava/lang/Integer;", methodCache: &decode_MethodID_15, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            throw NumberFormatException( javaObject: throwable )
        }
        return __return != nil ? Integer( javaObject: __return ) : nil
    }

    open class func decode( _ _arg0: String? ) throws /* java.lang.NumberFormatException */ -> Integer! {
        return try decode( arg0: _arg0 )
    }

    /// static java.lang.String java.lang.Integer.access$000()

    /// static void java.lang.Integer.getAndRemoveCacheProperties()

    /// public static int java.lang.Integer.reverse(int)

    private static var reverse_MethodID_16: jmethodID?

    open class func reverse( arg0: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "reverse", methodSig: "(I)I", methodCache: &reverse_MethodID_16, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func reverse( _ _arg0: Int ) -> Int {
        return reverse( arg0: _arg0 )
    }

    /// public static int java.lang.Integer.parseInt(java.lang.String) throws java.lang.NumberFormatException

    private static var parseInt_MethodID_17: jmethodID?

    open class func parseInt( arg0: String? ) throws /* java.lang.NumberFormatException */ -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "parseInt", methodSig: "(Ljava/lang/String;)I", methodCache: &parseInt_MethodID_17, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            throw NumberFormatException( javaObject: throwable )
        }
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func parseInt( _ _arg0: String? ) throws /* java.lang.NumberFormatException */ -> Int {
        return try parseInt( arg0: _arg0 )
    }

    /// public static int java.lang.Integer.parseInt(java.lang.String,int) throws java.lang.NumberFormatException

    private static var parseInt_MethodID_18: jmethodID?

    open class func parseInt( arg0: String?, arg1: Int ) throws /* java.lang.NumberFormatException */ -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "parseInt", methodSig: "(Ljava/lang/String;I)I", methodCache: &parseInt_MethodID_18, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            throw NumberFormatException( javaObject: throwable )
        }
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func parseInt( _ _arg0: String?, _ _arg1: Int ) throws /* java.lang.NumberFormatException */ -> Int {
        return try parseInt( arg0: _arg0, arg1: _arg1 )
    }

    /// public static java.lang.String java.lang.Integer.toOctalString(int)

    private static var toOctalString_MethodID_19: jmethodID?

    open class func toOctalString( arg0: Int ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "toOctalString", methodSig: "(I)Ljava/lang/String;", methodCache: &toOctalString_MethodID_19, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open class func toOctalString( _ _arg0: Int ) -> String! {
        return toOctalString( arg0: _arg0 )
    }

    /// public static java.lang.String java.lang.Integer.toBinaryString(int)

    private static var toBinaryString_MethodID_20: jmethodID?

    open class func toBinaryString( arg0: Int ) -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "toBinaryString", methodSig: "(I)Ljava/lang/String;", methodCache: &toBinaryString_MethodID_20, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }

    open class func toBinaryString( _ _arg0: Int ) -> String! {
        return toBinaryString( arg0: _arg0 )
    }

    /// private static java.lang.String java.lang.Integer.toUnsignedString(int,int)

    /// static int java.lang.Integer.stringSize(int)

    /// public static java.lang.Integer java.lang.Integer.getInteger(java.lang.String,java.lang.Integer)

    private static var getInteger_MethodID_21: jmethodID?

    open class func getInteger( arg0: String?, arg1: Integer? ) -> Integer! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "getInteger", methodSig: "(Ljava/lang/String;Ljava/lang/Integer;)Ljava/lang/Integer;", methodCache: &getInteger_MethodID_21, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Integer( javaObject: __return ) : nil
    }

    open class func getInteger( _ _arg0: String?, _ _arg1: Integer? ) -> Integer! {
        return getInteger( arg0: _arg0, arg1: _arg1 )
    }

    /// public static java.lang.Integer java.lang.Integer.getInteger(java.lang.String)

    private static var getInteger_MethodID_22: jmethodID?

    open class func getInteger( arg0: String? ) -> Integer! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "getInteger", methodSig: "(Ljava/lang/String;)Ljava/lang/Integer;", methodCache: &getInteger_MethodID_22, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Integer( javaObject: __return ) : nil
    }

    open class func getInteger( _ _arg0: String? ) -> Integer! {
        return getInteger( arg0: _arg0 )
    }

    /// public static java.lang.Integer java.lang.Integer.getInteger(java.lang.String,int)

    private static var getInteger_MethodID_23: jmethodID?

    open class func getInteger( arg0: String?, arg1: Int ) -> Integer! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "getInteger", methodSig: "(Ljava/lang/String;I)Ljava/lang/Integer;", methodCache: &getInteger_MethodID_23, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Integer( javaObject: __return ) : nil
    }

    open class func getInteger( _ _arg0: String?, _ _arg1: Int ) -> Integer! {
        return getInteger( arg0: _arg0, arg1: _arg1 )
    }

    /// public static int java.lang.Integer.highestOneBit(int)

    private static var highestOneBit_MethodID_24: jmethodID?

    open class func highestOneBit( arg0: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "highestOneBit", methodSig: "(I)I", methodCache: &highestOneBit_MethodID_24, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func highestOneBit( _ _arg0: Int ) -> Int {
        return highestOneBit( arg0: _arg0 )
    }

    /// public static int java.lang.Integer.lowestOneBit(int)

    private static var lowestOneBit_MethodID_25: jmethodID?

    open class func lowestOneBit( arg0: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "lowestOneBit", methodSig: "(I)I", methodCache: &lowestOneBit_MethodID_25, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func lowestOneBit( _ _arg0: Int ) -> Int {
        return lowestOneBit( arg0: _arg0 )
    }

    /// public static int java.lang.Integer.rotateLeft(int,int)

    private static var rotateLeft_MethodID_26: jmethodID?

    open class func rotateLeft( arg0: Int, arg1: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "rotateLeft", methodSig: "(II)I", methodCache: &rotateLeft_MethodID_26, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func rotateLeft( _ _arg0: Int, _ _arg1: Int ) -> Int {
        return rotateLeft( arg0: _arg0, arg1: _arg1 )
    }

    /// public static int java.lang.Integer.rotateRight(int,int)

    private static var rotateRight_MethodID_27: jmethodID?

    open class func rotateRight( arg0: Int, arg1: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "rotateRight", methodSig: "(II)I", methodCache: &rotateRight_MethodID_27, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func rotateRight( _ _arg0: Int, _ _arg1: Int ) -> Int {
        return rotateRight( arg0: _arg0, arg1: _arg1 )
    }

    /// public static int java.lang.Integer.signum(int)

    private static var signum_MethodID_28: jmethodID?

    open class func signum( arg0: Int ) -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Integer", classCache: &IntegerJNIClass, methodName: "signum", methodSig: "(I)I", methodCache: &signum_MethodID_28, args: &__args, locals: &__locals )
        return JNIType.decode( type: Int(), from: __return )
    }

    open class func signum( _ _arg0: Int ) -> Int {
        return signum( arg0: _arg0 )
    }

}
