
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.lang.reflect.InvocationTargetException ///

open class InvocationTargetException: ReflectiveOperationException {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var InvocationTargetExceptionJNIClass: jclass?

    /// private static final long java.lang.reflect.InvocationTargetException.serialVersionUID

    /// private java.lang.Throwable java.lang.reflect.InvocationTargetException.target

    /// static final long java.lang.ReflectiveOperationException.serialVersionUID

    /// static final long java.lang.Exception.serialVersionUID

    /// private static final long java.lang.Throwable.serialVersionUID

    /// private java.lang.String java.lang.Throwable.detailMessage

    /// private static final java.lang.StackTraceElement[] java.lang.Throwable.UNASSIGNED_STACK

    /// private java.lang.Throwable java.lang.Throwable.cause

    /// private java.lang.StackTraceElement[] java.lang.Throwable.stackTrace

    /// private static final java.util.List java.lang.Throwable.SUPPRESSED_SENTINEL

    /// private java.util.List java.lang.Throwable.suppressedExceptions

    /// private static final java.lang.String java.lang.Throwable.NULL_CAUSE_MESSAGE

    /// private static final java.lang.String java.lang.Throwable.SELF_SUPPRESSION_MESSAGE

    /// private static final java.lang.String java.lang.Throwable.CAUSE_CAPTION

    /// private static final java.lang.String java.lang.Throwable.SUPPRESSED_CAPTION

    /// private static final java.lang.Throwable[] java.lang.Throwable.EMPTY_THROWABLE_ARRAY

    /// static final boolean java.lang.Throwable.$assertionsDisabled

    /// public java.lang.reflect.InvocationTargetException(java.lang.Throwable,java.lang.String)

    private static var new_MethodID_1: jmethodID?

    public convenience init( target: java_swift.Throwable?, s: String? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: target != nil ? target! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: s, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/reflect/InvocationTargetException", classCache: &InvocationTargetException.InvocationTargetExceptionJNIClass, methodSig: "(Ljava/lang/Throwable;Ljava/lang/String;)V", methodCache: &InvocationTargetException.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _target: java_swift.Throwable?, _ _s: String? ) {
        self.init( target: _target, s: _s )
    }

    /// public java.lang.reflect.InvocationTargetException(java.lang.Throwable)

    private static var new_MethodID_2: jmethodID?

    public convenience init( target: java_swift.Throwable? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: target != nil ? target! as JNIObject : nil, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/reflect/InvocationTargetException", classCache: &InvocationTargetException.InvocationTargetExceptionJNIClass, methodSig: "(Ljava/lang/Throwable;)V", methodCache: &InvocationTargetException.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _target: java_swift.Throwable? ) {
        self.init( target: _target )
    }

    /// protected java.lang.reflect.InvocationTargetException()

    private static var new_MethodID_3: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "java/lang/reflect/InvocationTargetException", classCache: &InvocationTargetException.InvocationTargetExceptionJNIClass, methodSig: "()V", methodCache: &InvocationTargetException.new_MethodID_3, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public java.lang.Throwable java.lang.reflect.InvocationTargetException.getCause()

    /// public java.lang.Throwable java.lang.reflect.InvocationTargetException.getTargetException()

    private static var getTargetException_MethodID_4: jmethodID?

    open func getTargetException() -> java_swift.Throwable! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getTargetException", methodSig: "()Ljava/lang/Throwable;", methodCache: &InvocationTargetException.getTargetException_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.Throwable( javaObject: __return ) : nil
    }


}

