
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:25 GMT 2016 ///

/// interface java.lang.Iterable ///

public protocol Iterable: JavaProtocol {

    /// public abstract java.util.Iterator java.lang.Iterable.iterator()

}

open class IterableForward: JNIObjectForward, Iterable {

    private static var IterableJNIClass: jclass?

    /// public abstract java.util.Iterator java.lang.Iterable.iterator()

}


