
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.lang.Iterable ///

public protocol Iterable: JavaProtocol {

    /// public abstract java.util.Iterator java.lang.Iterable.iterator()

    /// public default java.util.Spliterator java.lang.Iterable.spliterator()

    /// public default void java.lang.Iterable.forEach(java.util.function.Consumer)

}


open class IterableForward: JNIObjectForward, Iterable {

    private static var IterableJNIClass: jclass?

    /// public abstract java.util.Iterator java.lang.Iterable.iterator()

    /// public default java.util.Spliterator java.lang.Iterable.spliterator()

    /// public default void java.lang.Iterable.forEach(java.util.function.Consumer)

}


