
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:05 GMT 2016 ///

/// interface java.lang.management.MemoryManagerMXBean ///

public protocol MemoryManagerMXBean: JavaProtocol {

    /// public abstract java.lang.String java.lang.management.MemoryManagerMXBean.getName()

    func getName() -> String!

    /// public abstract boolean java.lang.management.MemoryManagerMXBean.isValid()

    func isValid() -> Bool

    /// public abstract java.lang.String[] java.lang.management.MemoryManagerMXBean.getMemoryPoolNames()

    func getMemoryPoolNames() -> [String]!

}

open class MemoryManagerMXBeanForward: JNIObjectForward, MemoryManagerMXBean {

    private static var MemoryManagerMXBeanJNIClass: jclass?

    /// public abstract java.lang.String java.lang.management.MemoryManagerMXBean.getName()

    private static var getName_MethodID_4: jmethodID?

    open func getName() -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getName", methodSig: "()Ljava/lang/String;", methodCache: &MemoryManagerMXBeanForward.getName_MethodID_4, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }


    /// public abstract boolean java.lang.management.MemoryManagerMXBean.isValid()

    private static var isValid_MethodID_5: jmethodID?

    open func isValid() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isValid", methodSig: "()Z", methodCache: &MemoryManagerMXBeanForward.isValid_MethodID_5, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// public abstract java.lang.String[] java.lang.management.MemoryManagerMXBean.getMemoryPoolNames()

    private static var getMemoryPoolNames_MethodID_6: jmethodID?

    open func getMemoryPoolNames() -> [String]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getMemoryPoolNames", methodSig: "()[Ljava/lang/String;", methodCache: &MemoryManagerMXBeanForward.getMemoryPoolNames_MethodID_6, args: &__args, locals: &__locals )
        return JNIType.decode( type: [String](), from: __return )
    }


}


