
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.lang.invoke.MutableCallSite ///

open class MutableCallSite: CallSite {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var MutableCallSiteJNIClass: jclass?

    /// private static final java.util.concurrent.atomic.AtomicInteger java.lang.invoke.MutableCallSite.STORE_BARRIER

    /// java.lang.invoke.MethodHandle java.lang.invoke.CallSite.target

    /// private static final java.lang.invoke.MethodHandle java.lang.invoke.CallSite.GET_TARGET

    /// private static final java.lang.invoke.MethodHandle java.lang.invoke.CallSite.THROW_UCS

    /// private static final long java.lang.invoke.CallSite.TARGET_OFFSET

    /// public java.lang.invoke.MutableCallSite(java.lang.invoke.MethodType)

    private static var new_MethodID_1: jmethodID?

    public convenience init( type: MethodType? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: type != nil ? type! as JNIObject : nil, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/invoke/MutableCallSite", classCache: &MutableCallSite.MutableCallSiteJNIClass, methodSig: "(Ljava/lang/invoke/MethodType;)V", methodCache: &MutableCallSite.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _type: MethodType? ) {
        self.init( type: _type )
    }

    /// public java.lang.invoke.MutableCallSite(java.lang.invoke.MethodHandle)

    private static var new_MethodID_2: jmethodID?

    public convenience init( target: MethodHandle? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: target != nil ? target! as JNIObject : nil, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/invoke/MutableCallSite", classCache: &MutableCallSite.MutableCallSiteJNIClass, methodSig: "(Ljava/lang/invoke/MethodHandle;)V", methodCache: &MutableCallSite.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _target: MethodHandle? ) {
        self.init( target: _target )
    }

    /// public final java.lang.invoke.MethodHandle java.lang.invoke.MutableCallSite.dynamicInvoker()

    /// public final java.lang.invoke.MethodHandle java.lang.invoke.MutableCallSite.getTarget()

    /// public void java.lang.invoke.MutableCallSite.setTarget(java.lang.invoke.MethodHandle)

    private static var setTarget_MethodID_3: jmethodID?

    open func setTarget( newTarget: MethodHandle? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: newTarget != nil ? newTarget! as JNIObject : nil, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setTarget", methodSig: "(Ljava/lang/invoke/MethodHandle;)V", methodCache: &MutableCallSite.setTarget_MethodID_3, args: &__args, locals: &__locals )
    }

    override open func setTarget( _ _newTarget: MethodHandle? ) {
        setTarget( newTarget: _newTarget )
    }

    /// public static void java.lang.invoke.MutableCallSite.syncAll(java.lang.invoke.MutableCallSite[])

    private static var syncAll_MethodID_4: jmethodID?

    open class func syncAll( sites: [MutableCallSite]? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: sites, locals: &__locals )
        JNIMethod.CallStaticVoidMethod( className: "java/lang/invoke/MutableCallSite", classCache: &MutableCallSiteJNIClass, methodName: "syncAll", methodSig: "([Ljava/lang/invoke/MutableCallSite;)V", methodCache: &syncAll_MethodID_4, args: &__args, locals: &__locals )
    }

    open class func syncAll( _ _sites: [MutableCallSite]? ) {
        syncAll( sites: _sites )
    }

}

