
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:02 GMT 2016 ///

/// interface java.lang.Override ///

public protocol Override: Annotation {

}

open class OverrideForward: AnnotationForward, Override {

    private static var OverrideJNIClass: jclass?

}


