
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.lang.annotation.Target ///

public protocol Target: Annotation {

    /// public abstract java.lang.annotation.ElementType[] java.lang.annotation.Target.value()

    func value() -> [ElementType]!

}


open class TargetForward: AnnotationForward, Target {

    private static var TargetJNIClass: jclass?

    /// public abstract java.lang.annotation.ElementType[] java.lang.annotation.Target.value()

    private static var value_MethodID_2: jmethodID?

    open func value() -> [ElementType]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "value", methodSig: "()[Ljava/lang/annotation/ElementType;", methodCache: &TargetForward.value_MethodID_2, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [ElementType](), from: __return )
    }


    /// public abstract boolean java.lang.annotation.Annotation.equals(java.lang.Object)

    private static var equals_MethodID_3: jmethodID?

    override open func equals( obj: java_swift.JavaObject? ) -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: obj, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "equals", methodSig: "(Ljava/lang/Object;)Z", methodCache: &TargetForward.equals_MethodID_3, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Bool(), from: __return )
    }

    override open func equals( _ _obj: java_swift.JavaObject? ) -> Bool {
        return equals( obj: _obj )
    }

    /// public abstract java.lang.String java.lang.annotation.Annotation.toString()

    private static var toString_MethodID_4: jmethodID?

    override open func toString() -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "toString", methodSig: "()Ljava/lang/String;", methodCache: &TargetForward.toString_MethodID_4, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: String(), from: __return )
    }


    /// public abstract int java.lang.annotation.Annotation.hashCode()

    private static var hashCode_MethodID_5: jmethodID?

    override open func hashCode() -> Int {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "hashCode", methodSig: "()I", methodCache: &TargetForward.hashCode_MethodID_5, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Int(), from: __return )
    }


    /// public abstract java.lang.Class java.lang.annotation.Annotation.annotationType()

    private static var annotationType_MethodID_6: jmethodID?

    override open func annotationType() -> java_swift.JavaClass! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "annotationType", methodSig: "()Ljava/lang/Class;", methodCache: &TargetForward.annotationType_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaClass( javaObject: __return ) : nil
    }


}


