
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:29:25 GMT 2016 ///

/// interface java.lang.reflect.Type ///

public protocol Type: JavaProtocol {

}

open class TypeForward: JNIObjectForward, Type {

    private static var TypeJNIClass: jclass?

}


